function plotandlabel(data, fitresults, xoffset)
%% data and fitresults files
% xoffset for label in fig. 0<x<1

    figure('units','normalized','position',[.2 0.2 .7 .4]);hold on;
    plot(data.wavemeter', data.lockinavg, 'b.');
    plot(data.wavemeter', fitresults.fit(fitresults.x),'r');

    xlabel('frequency [THz]'); ylabel('lock in output [arb. units]');
    legend('data',...
        strjoin({'fit to gaussians, adj. R^2=',num2str(fitresults.Rsq,3)}),...
        'location','northwest'); 
    ax=gca;
    text(ax.XLim(1)+(diff(ax.XLim)*xoffset), sum(ax.YLim)/2,...
        {strjoin({'fwhm-L:',num2str(fitresults.fwhm(1),2),'\pm',...
        num2str(fitresults.fwhmerror(1),1),'MHz'}),...
        strjoin({'fwhm-R:',num2str(fitresults.fwhm(2),2),'\pm',...
        num2str(fitresults.fwhmerror(2),1),'MHz'}),...
        strjoin({'sep.:',num2str(fitresults.sep,3),'\pm',...
        num2str(fitresults.seperror,1),' MHz'}),...
        strjoin({'PSNR:',num2str(fitresults.psnr,2),'dB'}) ...
%         strjoin({'SNR:',num2str(fitresults.snr,2),'\pm',...
%          num2str(fitresults.snrerror,1)}) ...
         });

    title(strjoin({data.filename, '(',date,')'}));

    set(gca,'Fontsize',12);
end